#!/bin/bash

set -e

if [[ -n "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
"Usage: $(basename "$0")

Build container images from templates.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        sed -e "s/%%GDAL_VERSION%%/$GDAL_VERSION/" \
            -e "s/%%OPENJPEG_VERSION%%/$OPENJPEG_VERSION/" \
            -e "s/%%ANT_VERSION%%/$ANT_VERSION/" \
            "Dockerfile-$VARIANT.template" > Dockerfile

        docker build -t "quay.io/azavea/openjdk-gdal:$GDAL_VERSION-$VARIANT" .

        ./scripts/test

        docker images
    fi
fi
