#!/bin/bash

set -e

if [[ -n "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
"Usage: $(basename "$0")

Test container images built from templates.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        docker run --rm \
                   --entrypoint gdalinfo \
                   "quay.io/azavea/openjdk-gdal:$GDAL_VERSION-jdk$OPENJDK_VERSION-$VARIANT" \
                   --version

        docker run --rm \
                   --entrypoint gdalinfo \
                   "quay.io/azavea/openjdk-gdal:$GDAL_VERSION-jdk$OPENJDK_VERSION-$VARIANT" \
                   --formats

        docker run --rm \
                   --entrypoint ogrinfo \
                   "quay.io/azavea/openjdk-gdal:$GDAL_VERSION-jdk$OPENJDK_VERSION-$VARIANT" \
                   --formats
    fi
fi

